// Vue-CLI/02_project_vite/src/App.vue
<template>
    <div>App</div>
    <h2>{{ price }}</h2>
    <app-header></app-header>
</template>

<script>
import AppHeader from './components/AppHeader.vue';
export default {
    name: "App",
    data() {
      return {
        price: 999
      }
    },
    components: {
      AppHeader
    }
}
</script>

<style scoped>
    
</style>

// airbnb/src/App.jsx
import {memo} from "react";
import {useRoutes} from "react-router-dom";
import routes from "@/router";
import AppHeader from "@/components/app-header";
import AppFooter from "@/components/app-footer";

const App = memo(() => {
  return (
    <div className="app">
      <AppHeader/>
      <div className="page">
        {useRoutes(routes)}
      </div>
      <AppFooter/>
    </div>
  )
})

export default App
